#  TUGAS ARRAY

#PERKALIAN MATRIX

In [6]:
import numpy as np

# Diketahui vektor-vektor A, B, dan C
A = np.array([56, 4, 2])
B = np.array([3, 43, 21])
C = np.array([32, 66, 13])

# Membentuk matriks M dari vektor-vektor tersebut
M = np.array([A, B, C])

# Menghitung perkalian matriks M x M x M
result = np.dot(np.dot(M, M), M)

# Menampilkan hasil
print("Hasil perkalian matriks M x M x M adalah:")
print(result)

Hasil perkalian matriks M x M x M adalah:
[[188560  50204  20398]
 [101829 221509  85491]
 [198016 280910 106163]]


In [ ]:
PENJELASAN: 
1. Mengimport numpy yang merupakan pustaka Python yang digunakan untuk bekerja dengan array dan matriks.
2. mendefinisikan tiga vektor A, B, dan C menggunakan np.array, yang merupakan cara untuk membuat array NumPy.
3. membentuk matriks M dengan menggabungkan vektor-vektor A, B, dan C menjadi satu matriks. Matriks M sekarang adalah
   matriks 3x3 dengan setiap barisnya adalah salah satu vektor.
4. np.dot(np.dot(M, M), M) kemudian mengalikan hasil dari M x M dengan M lagi (yang menghasilkan matriks hasil kali M x M x M).
5.  mencetak string "Hasil perkalian matriks M x M x M adalah:" diikuti dengan hasil perkalian matriks M x M x M.

#PENGURANGAN MATRIX

In [4]:
import numpy as np

# Diketahui matriks A
A = np.array([56, 4, 2])
B = np.array([3, 43, 21])
C = np.array([32, 66, 13])

# Menghitung pengurangan matriks
result = A - B - C

# Menampilkan hasil
print("Hasil pengurangan matriks A - B - C adalah:")
print(result)

Hasil pengurangan matriks A - B - C adalah:
[  21 -105  -32]


In [ ]:
PENJELASAN: 
1. Mengimport numpy yang merupakan pustaka Python yang digunakan untuk bekerja dengan array dan matriks.
2. mendefinisikan tiga vektor A, B, dan C menggunakan np.array.
3. Operasi A - B mengurangkan elemen-elemen vektor B dari elemen-elemen vektor A.
Kemudian hasil dari A - B dikurangi lagi dengan elemen-elemen vektor C. 
CONTOH: Elemen pertama:56−3−32=21
4. mencetak string "Hasil pengurangan matriks A - B - C adalah:" diikuti dengan hasil pengurangan vektor A, B, dan C.

#TRANSPOSE MATRIX

In [7]:
import numpy as np

# Diketahui matriks A sebagai matriks 2D
A = np.array([[56, 4, 2],
              [3, 43, 21],
              [32, 66, 13]])

# Menghitung transpose matriks A
transpose = np.transpose(A)

# Menampilkan hasil
print("Transpose dari matriks A adalah:")
print(transpose)

Transpose dari matriks A adalah:
[[56  3 32]
 [ 4 43 66]
 [ 2 21 13]]


In [ ]:
PENJELASAN: 
1. Mengimport numpy yang merupakan pustaka Python yang digunakan untuk bekerja dengan array dan matriks.
2. mendefinisikan tiga vektor A, B, dan C menggunakan np.array.
3. menghitung transpose dari matriks 2D
4. mencetak string "Transpose dari matriks A adalah:" yang memindahkan posisi elemen-elemen string dari baris menjadi kolom 


#NILAI INVERS

In [8]:
import numpy as np

# Diketahui vektor-vektor A, B, dan C
A = np.array([56, 4, 2])
B = np.array([3, 43, 21])
C = np.array([32, 66, 13])

# Membentuk matriks M dari vektor-vektor tersebut
M = np.array([A, B, C])

try:
    # Menghitung invers matriks M
    M_inv = np.linalg.inv(M)
    print("Invers dari matriks M adalah:")
    print(M_inv)
except np.linalg.LinAlgError:
    print("Matriks tidak memiliki invers (determinannya nol).")

Invers dari matriks M adalah:
[[ 1.79252644e-02 -1.73400381e-03  4.33500954e-05]
 [-1.37203052e-02 -1.43922317e-02  2.53598058e-02]
 [ 2.55332062e-02  7.73365701e-02 -5.19334143e-02]]


In [ ]:
PENJELASAN:
1. Mengimpor NumPy dengan alias np.
2. Mendefinisikan tiga vektor A, B, dan C.
3. Membentuk matriks M dari vektor-vektor tersebut.
4. Menghitung invers dari matriks M menggunakan np.linalg.inv(M).
5. Mencetak hasil invers matriks M.

#NILAI DETERMINAN

In [9]:
import numpy as np

# Diketahui vektor-vektor A, B, dan C
A = np.array([56, 4, 2])
B = np.array([3, 43, 21])
C = np.array([32, 66, 13])

# Membentuk matriks M dari vektor-vektor tersebut
M = np.array([A, B, C])

# Menghitung determinan matriks
det_M = np.linalg.det(M)

# Menampilkan hasil
print(f"Determinan dari matriks M adalah: {det_M}")

Determinan dari matriks M adalah: -46136.000000000044


In [ ]:
PENJELASAN: 
1. Mengimport numpy yang merupakan pustaka Python yang digunakan untuk bekerja dengan array dan matriks.
2. mendefinisikan tiga vektor A, B, dan C menggunakan np.array.
3. M = np.array([A, B, C]): ini menggabungkan vektor-vektor A, B, dan C menjadi satu matriks 
4. det_M = np.linalg.det(M): ini menghitung determinan dari matriks M menggunakan fungsi np.linalg.det() dari NumPy
5. print(f"Determinan dari matriks M adalah: {det_M}"): ini mencetak hasil perhitungan determinan matriks M ke layar.